apiVersion: v1
kind: Pod
metadata:
  name: test-prefilter-1
  labels:
    podGroup: "GP"
    minAvailable: "3"
spec:
  schedulerName: my-scheduler
  containers:
  - name: nginx
    image: nginx:1.14.2
    resources:
      requests:
        memory: "100Mi"
      limits:
        memory: "100Mi"
---
apiVersion: v1
kind: Pod
metadata:
  name: test-prefilter-2
  labels:
    podGroup: "GP"
    minAvailable: "3"
spec:
  schedulerName: my-scheduler
  containers:
  - name: nginx
    image: nginx:1.14.2
    resources:
      requests:
        memory: "100Mi"
      limits:
        memory: "100Mi"
---
apiVersion: v1
kind: Pod
metadata:
  name: test-prefilter-3
  labels:
    podGroup: "GP"
    minAvailable: "3"
spec:
  schedulerName: my-scheduler
  containers:
  - name: nginx
    image: nginx:1.14.2
    resources:
      requests:
        memory: "100Mi"
      limits:
        memory: "100Mi"