apiVersion: v1
kind: Pod
metadata:
  name: test-most-1
  labels:
    podGroup: "GM"
    minAvailable: "1"
spec:
  schedulerName: my-scheduler
  containers:
  - name: nginx
    image: nginx:1.14.2
    resources:
      requests:
        memory: "1000Mi"
      limits:
        memory: "1000Mi"
---
apiVersion: v1
kind: Pod
metadata:
  name: test-most-2
  labels:
    podGroup: "GM"
    minAvailable: "1"
spec:
  schedulerName: my-scheduler
  containers:
  - name: nginx
    image: nginx:1.14.2
    resources:
      requests:
        memory: "100Mi"
      limits:
        memory: "100Mi"    